BEGIN;
CREATE TABLE IF NOT EXISTS users (
    id UUID DEFAULT uuidv7() PRIMARY KEY,
	email TEXT NOT NULL UNIQUE,
	username TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
COMMIT;
