BEGIN;
DROP TABLE IF EXISTS rel_rent_product;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS penalties;
DROP TABLE IF EXISTS rents;
DROP TABLE IF EXISTS customers;
DROP TYPE IF EXISTS ENUM_PENALTY_STATUS;
DROP TYPE IF EXISTS ENUM_PAYMENT_PURPOSE;
COMMIT;
