BEGIN;
CREATE TABLE IF NOT EXISTS customers (
    id UUID DEFAULT uuidv7() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NULL UNIQUE,
    phone VARCHAR(255) NOT NULL UNIQUE,
    contact JSONB DEFAULT '{}' NOT NULL,
    address VARCHAR(255) NOT NULL,
    zip VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);
CREATE TABLE IF NOT EXISTS rents (
    id UUID DEFAULT uuidv7() PRIMARY KEY,
    date_order BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    date_start BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    date_end BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    of_customer UUID NOT NULL REFERENCES customers(id),
    of_store UUID NOT NULL REFERENCES stores(id),
    of_branch UUID NOT NULL REFERENCES branches(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS rel_rent_product (
    id UUID DEFAULT uuidv7() PRIMARY KEY,
    of_rent UUID NOT NULL REFERENCES rents(id),
    of_product UUID NOT NULL REFERENCES products(id),
    price INTEGER NOT NULL DEFAULT 0,
    qty INTEGER NOT NULL DEFAULT 1
);

CREATE TYPE ENUM_PENALTY_STATUS AS ENUM ('pending', 'progress', 'completed');

CREATE TABLE IF NOT EXISTS penalties (
    id UUID DEFAULT uuidv7() PRIMARY KEY,
    of_rent UUID NOT NULL REFERENCES rents(id),
    amount INTEGER NOT NULL DEFAULT 0,
    description VARCHAR(1000) NOT NULL DEFAULT '',
    attachments VARCHAR(100)[] NOT NULL DEFAULT '{}',
    resolution VARCHAR(1000) NOT NULL DEFAULT '',
    status ENUM_PENALTY_STATUS NOT NULL DEFAULT 'pending',
    date_start BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    date_end BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TYPE ENUM_PAYMENT_PURPOSE AS ENUM ('deposit', 'close');

CREATE TABLE IF NOT EXISTS payments (
    id UUID DEFAULT uuidv7() PRIMARY KEY,
    of_rent UUID NOT NULL REFERENCES rents(id),
    of_customer UUID NOT NULL REFERENCES customers(id),
    of_branch UUID NOT NULL REFERENCES branches(id),
    of_penalty UUID NULL REFERENCES penalties(id),
    purpose ENUM_PAYMENT_PURPOSE NOT NULL DEFAULT 'deposit',
    amount INTEGER NOT NULL DEFAULT 0,
    notes VARCHAR(1000) NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

COMMIT;
