BEGIN;
CREATE TABLE storage (
	id UUID DEFAULT uuidv7() PRIMARY KEY,
	bucket VARCHAR(255) NOT NULL,
	path VARCHAR(255) NOT NULL,
	notes TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
COMMIT;
