// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Log struct {
	ID           pgtype.UUID `json:"id"`
	LogLevel     string      `json:"log_level"`
	Description  string      `json:"description"`
	FromFunction string      `json:"from_function"`
	CreatedAt    pgtype.Int8 `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Email     string           `json:"email"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
