// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q.log.sql

package db

import (
	"context"
)

const monitorLogs = `-- name: MonitorLogs :many
SELECT id, log_level, description, from_function, created_at FROM logs ORDER BY created_at DESC
`

func (q *Queries) MonitorLogs(ctx context.Context) ([]Log, error) {
	rows, err := q.db.Query(ctx, monitorLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.LogLevel,
			&i.Description,
			&i.FromFunction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
