// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q.product.sql

package db

import (
	"context"
)

const indexProducts = `-- name: IndexProducts :many
SELECT id, name, description, price, category, specification, of_store, created_at FROM products ORDER BY created_at DESC
`

func (q *Queries) IndexProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, indexProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.Specification,
			&i.OfStore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
