// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q.role.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const setupTenantRole = `-- name: SetupTenantRole :one
INSERT INTO roles (name, of_store)
VALUES ($1, $2)
RETURNING id, name, of_store, created_at
`

type SetupTenantRoleParams struct {
	Name    string      `json:"name"`
	OfStore pgtype.UUID `json:"of_store"`
}

func (q *Queries) SetupTenantRole(ctx context.Context, arg SetupTenantRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, setupTenantRole, arg.Name, arg.OfStore)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OfStore,
		&i.CreatedAt,
	)
	return i, err
}
